### ISSUE TITLE
useMeta hook does not remove meta elements on unmount

### ISSUE THREAD

**Issue by stufreen** [Shopify/quilt#1580]
## Overview

The `useMeta` hook from `react-html` (https://github.com/Shopify/quilt/tree/master/packages/react-html#usemeta-and-meta-) does not seem to remove meta elements when the calling component is unmounted.

E.g.
```
const MyScreen = () => {
  useMeta({name: 'description', content: 'seoDescription'});
  ...
}
```

I would expect the `meta` element to be removed from the dom tree when MyScreen is unmounted. However, it leaves the element in the dom tree. This can lead to many conflicting `meta` elements accumulating in the `head` as the user navigates around the app.

## Consuming repo

> What repo were you working in when this issue occurred?

shopify/start-web

### Area

- [x] Add any relevant `Area: <area>` labels to this issue

### Scope

- Is this issue related to a specific package?

  - [x] Tag it with the `Package: <package_name>` label.

---

## Checklist

- [ ] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)
