### ISSUE TITLE
Reduce console.log spam in quilt test runs

### ISSUE THREAD

**Issue by BPScott** [Shopify/quilt#2157]
## Overview

Running the unit tests is currently very noisy. There's a lot of console.log noise that you need to scroll through, which makes discovering failures harder than it needs to be. `CI=1 yarn run test` produces 1700 lines of noise, 200 of which are "PASS" lines. So about 7/8s of the output is noise.

## Task

Identify tests that produce noisy output and fix them:

- if the logspam is complaining about something then fix the issue it's complaining about
- if the logs are a required part of the test then mock console.log in the test so it doesn't output.

List of tests that are currently causing console.logs:

- [x] packages/logger/src/formatters/tests/ConsoleFormatter.test.ts
- [x] packages/react-async/src/tests/component.test.tsx
- [x] packages/react-async/src/tests/provider.test.tsx
- [x] packages/react-bugsnag/src/tests/Bugsnag.test.tsx
- [x] packages/react-csrf/src/tests/hooks.test.tsx
- [x] packages/react-form/src/hooks/list/tests/baselist.test.tsx
- [x] packages/react-form/src/hooks/list/tests/dynamiclist.test.tsx
- [x] packages/react-form-state/src/components/tests/List.test.tsx
- [x] packages/react-form-state/src/components/tests/Nested.test.tsx
- [x] packages/react-form-state/src/tests/FormState.test.tsx
- [x] packages/react-graphql/src/async/tests/component.test.tsx
- [x] packages/react-graphql-universal-provider/src/tests/GraphQLUniversalProvider.test.tsx
- [x] packages/react-html/src/server/components/tests/Html.test.tsx
- [x] packages/react-import-remote/src/tests/ImportRemote.test.tsx
- [x] packages/react-network/src/tests/NetworkUniversalProvider.test.tsx
- [x] packages/react-router/src/components/Router/tests/Router.test.tsx
- [x] packages/react-server/src/render/tests/render.test.tsx
- [x] packages/react-server/src/server/tests/server.test.tsx
- [x] packages/react-testing/src/tests/root.test.tsx
- [x] packages/storybook-a11y-test/tests/index.test.ts
- [x] packages/web-worker/src/tests/e2e.test.ts

**Comment by ryanwilsonperkin** [comment]
In the past I've done something to the effect of:

```js
// setup-each.js
console.log = () => throw 'console.log is banned!';
console.error = () => throw 'console.error is banned!';
```

Maybe getting a bit fancier with the args and showing what the original message was intended to be. If tests still want to console log, they have to explicitly mock it out instead, which has the added benefit of encouraging them to assert on the outcome.

**Comment by BPScott** [comment]
List of tests that are currently causing console.logs:

packages/logger/src/formatters/tests/ConsoleFormatter.test.ts
packages/react-async/src/tests/component.test.tsx
packages/react-async/src/tests/provider.test.tsx
packages/react-bugsnag/src/tests/Bugsnag.test.tsx
packages/react-csrf/src/tests/hooks.test.tsx
packages/react-form/src/hooks/list/tests/baselist.test.tsx
packages/react-form/src/hooks/list/tests/dynamiclist.test.tsx
packages/react-form-state/src/components/tests/List.test.tsx
packages/react-form-state/src/components/tests/Nested.test.tsx
packages/react-form-state/src/tests/FormState.test.tsx
packages/react-graphql/src/async/tests/component.test.tsx
packages/react-graphql-universal-provider/src/tests/GraphQLUniversalProvider.test.tsx
packages/react-html/src/server/components/tests/Html.test.tsx
packages/react-import-remote/src/tests/ImportRemote.test.tsx
packages/react-network/src/tests/NetworkUniversalProvider.test.tsx
packages/react-router/src/components/Router/tests/Router.test.tsx
packages/react-server/src/render/tests/render.test.tsx
packages/react-server/src/server/tests/server.test.tsx
packages/react-testing/src/tests/root.test.tsx
packages/storybook-a11y-test/tests/index.test.ts
packages/web-worker/src/tests/e2e.test.ts

**Comment by BPScott** [comment]
List of tests that are currently causing console.logs:

packages/logger/src/formatters/tests/ConsoleFormatter.test.ts
packages/react-async/src/tests/component.test.tsx
packages/react-async/src/tests/provider.test.tsx
packages/react-bugsnag/src/tests/Bugsnag.test.tsx
packages/react-csrf/src/tests/hooks.test.tsx
packages/react-form/src/hooks/list/tests/baselist.test.tsx
packages/react-form/src/hooks/list/tests/dynamiclist.test.tsx
packages/react-form-state/src/components/tests/List.test.tsx
packages/react-form-state/src/components/tests/Nested.test.tsx
packages/react-form-state/src/tests/FormState.test.tsx
packages/react-graphql/src/async/tests/component.test.tsx
packages/react-graphql-universal-provider/src/tests/GraphQLUniversalProvider.test.tsx
packages/react-html/src/server/components/tests/Html.test.tsx
packages/react-import-remote/src/tests/ImportRemote.test.tsx
packages/react-network/src/tests/NetworkUniversalProvider.test.tsx
packages/react-router/src/components/Router/tests/Router.test.tsx
packages/react-server/src/render/tests/render.test.tsx
packages/react-server/src/server/tests/server.test.tsx
packages/react-testing/src/tests/root.test.tsx
packages/storybook-a11y-test/tests/index.test.ts
packages/web-worker/src/tests/e2e.test.ts
