### ISSUE TITLE
:sparkles: react-i18n: expose getShortCurrencySymbol as a public method and add list of exceptions for currencies that should not be shortened  

### ISSUE THREAD

**Issue by zaquille-oneil** [Shopify/quilt#2265]
## Overview
There are two parts to this feature request.
### Part 1 Make `getShortCurrencySymbol` public
Currently `getShortCurrencySymbol` is a private method that is utilized to display symbols for currencies when shown next to a number amount. 
for example:
 - for `CAD`, the `$` is the short symbol in `$ 5.00` as opposed to a long symbol `CA$` in `CA$ 5.00`
 - `€` in `€ 1,25 EUR`

https://github.com/Shopify/quilt/pull/916 introduced this method in order to support `formatCurrency` when showing a dollar amount. However, there are new use cases in web where we would like to surface this symbol _without_ a dollar amount (https://github.com/Shopify/core-issues/issues/36529). 

### Part 2 Add a currency exception list
In efforts to unify the rendering logic around currency symbols, we need to add a list of currencies that should be exceptions to the rule when shortening a symbol. As of right now, these two currencies should include BRL (Brazilian Real) and HKD (Hong Kong Dollar) which should show the full-length symbol across Shopify (`R$` and `HK$` respectively). These two values should not be shortened. 

This change has already been made to mobile surfaces (https://github.com/Shopify/mobile/blob/main/android/Foundation/Util/src/main/java/com/shopify/foundation/util/NumberFormatter.kt) and @shopify-i18n (https://github.com/Shopify/shopify-i18n/blob/069e3c846acb257cc761548d45612919f629966e/lib/shopify-i18n/currency.rb#L8)

## Type

- [x] New feature
- [x] Changes to existing features

## Motivation
While working on a new feature (multi-currency support for the B2B Pricing project), I noticed inconsistencies with how we display shortened currency symbols.

### Area

- [ ] Add any relevant `Area: <area>` labels to this issue

### Scope

- Is this issue related to a specific package?

  - [x] Tag it with the `Package: <package_name>` label.

- Is it related to a new package?
  - [ ] Tag it with the `New package` Label

---

## Checklist

- [ ] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)
